/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package api;

/**
 *
 * @author Peter
 */
public enum ITEM {

    DAGGER("% dagger", "Dagger", new MATERIAL[] {MATERIAL.BRONZE, MATERIAL.IRON, MATERIAL.SILVER, MATERIAL.STEEL, MATERIAL.GOLD, MATERIAL.MITHRIL, MATERIAL.ADAMANTITE, MATERIAL.RUNITE}, 1),
    AXE("% axe", "Axe", new MATERIAL[] {MATERIAL.BRONZE, MATERIAL.IRON, MATERIAL.SILVER, MATERIAL.STEEL, MATERIAL.GOLD, MATERIAL.MITHRIL, MATERIAL.ADAMANTITE, MATERIAL.RUNITE}, 1),
    MACE("% mace", "Mace", new MATERIAL[] {MATERIAL.BRONZE, MATERIAL.IRON, MATERIAL.SILVER, MATERIAL.STEEL, MATERIAL.GOLD, MATERIAL.MITHRIL, MATERIAL.ADAMANTITE, MATERIAL.RUNITE}, 1),
    MEDHELM("% med helm", "Medium helm", new MATERIAL[] {MATERIAL.BRONZE, MATERIAL.IRON, MATERIAL.SILVER, MATERIAL.STEEL, MATERIAL.GOLD, MATERIAL.MITHRIL, MATERIAL.ADAMANTITE, MATERIAL.RUNITE}, 1),
    //BOLTS("% bolts", "", new MATERIAL[] {MATERIAL.BRONZE, MATERIAL.IRON, MATERIAL.SILVER, MATERIAL.STEEL, MATERIAL.GOLD, MATERIAL.MITHRIL, MATERIAL.ADAMANTITE, MATERIAL.RUNITE}, 1),
    SWORD("% sword", "Sword", new MATERIAL[] {MATERIAL.BRONZE, MATERIAL.IRON, MATERIAL.SILVER, MATERIAL.STEEL, MATERIAL.GOLD, MATERIAL.MITHRIL, MATERIAL.ADAMANTITE, MATERIAL.RUNITE}, 1),
    WIRE("Bronze wire", "Bronze wire", new MATERIAL[] {MATERIAL.BRONZE}, 1),
    DARTTIP("% dart tip", "Dart tips", new MATERIAL[] {MATERIAL.BRONZE, MATERIAL.IRON, MATERIAL.SILVER, MATERIAL.STEEL, MATERIAL.GOLD, MATERIAL.MITHRIL, MATERIAL.ADAMANTITE, MATERIAL.RUNITE}, 1),
    NAIL("% nails", "Nails", new MATERIAL[] {MATERIAL.BRONZE, MATERIAL.IRON, MATERIAL.SILVER, MATERIAL.STEEL, MATERIAL.GOLD, MATERIAL.MITHRIL, MATERIAL.ADAMANTITE, MATERIAL.RUNITE}, 1),
    ARROWTIPS("% arrowtips", "Arrowtips", new MATERIAL[] {MATERIAL.BRONZE, MATERIAL.IRON, MATERIAL.SILVER, MATERIAL.STEEL, MATERIAL.GOLD, MATERIAL.MITHRIL, MATERIAL.ADAMANTITE, MATERIAL.RUNITE}, 1),
    SCIMITAR("% scimitar", "Scimitar", new MATERIAL[] {MATERIAL.BRONZE, MATERIAL.IRON, MATERIAL.SILVER, MATERIAL.STEEL, MATERIAL.GOLD, MATERIAL.MITHRIL, MATERIAL.ADAMANTITE, MATERIAL.RUNITE}, 2),
    //LIMBS("% limbs", "", new MATERIAL[] {MATERIAL.BRONZE, MATERIAL.IRON, MATERIAL.SILVER, MATERIAL.STEEL, MATERIAL.GOLD, MATERIAL.MITHRIL, MATERIAL.ADAMANTITE, MATERIAL.RUNITE}, 1),
    LONGSWORD("% longsword", "Long sword", new MATERIAL[] {MATERIAL.BRONZE, MATERIAL.IRON, MATERIAL.SILVER, MATERIAL.STEEL, MATERIAL.GOLD, MATERIAL.MITHRIL, MATERIAL.ADAMANTITE, MATERIAL.RUNITE}, 2),
    //JAVELINHEAD("% javelin heads", "", new MATERIAL[] {MATERIAL.BRONZE, MATERIAL.IRON, MATERIAL.SILVER, MATERIAL.STEEL, MATERIAL.GOLD, MATERIAL.MITHRIL, MATERIAL.ADAMANTITE, MATERIAL.RUNITE}, 1),
    FULLHELM("% full helm", "Full helm", new MATERIAL[] {MATERIAL.BRONZE, MATERIAL.IRON, MATERIAL.SILVER, MATERIAL.STEEL, MATERIAL.GOLD, MATERIAL.MITHRIL, MATERIAL.ADAMANTITE, MATERIAL.RUNITE}, 2),
    KNIFE("% knife", "Knives", new MATERIAL[] {MATERIAL.BRONZE, MATERIAL.IRON, MATERIAL.SILVER, MATERIAL.STEEL, MATERIAL.GOLD, MATERIAL.MITHRIL, MATERIAL.ADAMANTITE, MATERIAL.RUNITE}, 1),
    SQUARESHIELD("% sq shield", "Square shield", new MATERIAL[] {MATERIAL.BRONZE, MATERIAL.IRON, MATERIAL.SILVER, MATERIAL.STEEL, MATERIAL.GOLD, MATERIAL.MITHRIL, MATERIAL.ADAMANTITE, MATERIAL.RUNITE}, 2),
    WARHAMMER("% warhammer", "Warhammer", new MATERIAL[] {MATERIAL.BRONZE, MATERIAL.IRON, MATERIAL.SILVER, MATERIAL.STEEL, MATERIAL.GOLD, MATERIAL.MITHRIL, MATERIAL.ADAMANTITE, MATERIAL.RUNITE}, 3),
    BATTLEAXE("% battleaxe", "Battle axe", new MATERIAL[] {MATERIAL.BRONZE, MATERIAL.IRON, MATERIAL.SILVER, MATERIAL.STEEL, MATERIAL.GOLD, MATERIAL.MITHRIL, MATERIAL.ADAMANTITE, MATERIAL.RUNITE}, 3),
    CHAINBODY("% chainbody", "Chain body", new MATERIAL[] {MATERIAL.BRONZE, MATERIAL.IRON, MATERIAL.SILVER, MATERIAL.STEEL, MATERIAL.GOLD, MATERIAL.MITHRIL, MATERIAL.ADAMANTITE, MATERIAL.RUNITE}, 3),
    KITESHIELD("% kiteshield", "Kite shield", new MATERIAL[] {MATERIAL.BRONZE, MATERIAL.IRON, MATERIAL.SILVER, MATERIAL.STEEL, MATERIAL.GOLD, MATERIAL.MITHRIL, MATERIAL.ADAMANTITE, MATERIAL.RUNITE}, 3),
    //CLAWS("% claws", "", new MATERIAL[] {MATERIAL.BRONZE, MATERIAL.IRON, MATERIAL.SILVER, MATERIAL.STEEL, MATERIAL.GOLD, MATERIAL.MITHRIL, MATERIAL.ADAMANTITE, MATERIAL.RUNITE}, 1),
    TWOHANDSWORD("% 2h sword", "2-hand sword", new MATERIAL[] {MATERIAL.BRONZE, MATERIAL.IRON, MATERIAL.SILVER, MATERIAL.STEEL, MATERIAL.GOLD, MATERIAL.MITHRIL, MATERIAL.ADAMANTITE, MATERIAL.RUNITE}, 3),
    PLATELEG("% platelegs", "Plate legs", new MATERIAL[] {MATERIAL.BRONZE, MATERIAL.IRON, MATERIAL.SILVER, MATERIAL.STEEL, MATERIAL.GOLD, MATERIAL.MITHRIL, MATERIAL.ADAMANTITE, MATERIAL.RUNITE}, 3),
    PLATESKIRT("% plateskirt", "Plate skirt", new MATERIAL[] {MATERIAL.BRONZE, MATERIAL.IRON, MATERIAL.SILVER, MATERIAL.STEEL, MATERIAL.GOLD, MATERIAL.MITHRIL, MATERIAL.ADAMANTITE, MATERIAL.RUNITE}, 3),
    PLATEBODY("% platebody", "Plate body", new MATERIAL[] {MATERIAL.BRONZE, MATERIAL.IRON, MATERIAL.SILVER, MATERIAL.STEEL, MATERIAL.GOLD, MATERIAL.MITHRIL, MATERIAL.ADAMANTITE, MATERIAL.RUNITE}, 5);

    /*
    Bronze wire (bronze)
    Iron spit (iron)
    Oil lantern frame (iron)
    Studs (steel)
    Bullseye lantern (steel)
    Cannonballs (steel)
    Mith grapple tip (mithril)
    */
    
    private final String name;
    private final String smithName;
    private final MATERIAL[] mats;
    private final int barCount;
    
    ITEM(String name, String smithName, MATERIAL[] mats, int barCount) {
        this.name = name;
        this.smithName = smithName;
        this.mats = mats;
        this.barCount = barCount;
    }

    public String getName(MATERIAL mat) {
        return hasItem(mat) ? getName().replace("%", mat.getName()) : null;
    }
    
    public boolean hasItem(MATERIAL mat) {
        for(MATERIAL m : getMaterials()) {
            if(m.equals(mat)) {
                return true;
            }
        }
        return false;
    }
    
    private String getName() {
        return name;
    }

    public String getSmithName() {
        return smithName;
    }
    
    public MATERIAL[] getMaterials() {
        return mats;
    }

    public int getBarCount() {
        return barCount;
    }

}
